### ISSUE TITLE
Plasma crashes sometimes

### ISSUE THREAD

**Issue by arcan1s** [arcan1s/awesome-widgets#116]
```
======= Backtrace: =========
/usr/lib/libc.so.6(+0x70c4b)[0x7fad72f44c4b]
/usr/lib/libc.so.6(+0x76fe6)[0x7fad72f4afe6]
/usr/lib/libc.so.6(+0x777de)[0x7fad72f4b7de]
/usr/lib/libQt5Core.so.5(+0x2ccb85)[0x7fad738c6b85]
/usr/lib/qt/qml/org/kde/plasma/private/awesomewidget/libawplugin.so(+0x42c93)[0x7facbd17ec93]
/usr/lib/qt/qml/org/kde/plasma/private/awesomewidget/libawplugin.so(+0x425d1)[0x7facbd17e5d1]
/usr/lib/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x639)[0x7fad738ac659]
/usr/lib/qt/qml/org/kde/plasma/private/awesomewidget/libawplugin.so(+0x95983)[0x7facbd1d1983]
/usr/lib/qt/qml/org/kde/plasma/private/awesomewidget/libawplugin.so(+0x75f40)[0x7facbd1b1f40]
/usr/lib/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x639)[0x7fad738ac659]
/usr/lib/libQt5Core.so.5(_ZN6QTimer10timerEventEP11QTimerEvent+0x28)[0x7fad738b96d8]
/usr/lib/libQt5Core.so.5(_ZN7QObject5eventEP6QEvent+0xa3)[0x7fad738ad473]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7fad747ebe0c]
/usr/lib/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x261)[0x7fad747f3581]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x110)[0x7fad73880de0]
/usr/lib/libQt5Core.so.5(_ZN14QTimerInfoList14activateTimersEv+0x48e)[0x7fad738d46ae]
/usr/lib/libQt5Core.so.5(+0x2dac09)[0x7fad738d4c09]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x2a7)[0x7fad6e27fe67]
/usr/lib/libglib-2.0.so.0(+0x4a0d0)[0x7fad6e2800d0]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7fad6e28017c]
/usr/lib/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f)[0x7fad738d570f]
/usr/lib/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0xfa)[0x7fad7387f23a]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x9c)[0x7fad7388773c]
plasmashell[0x41b54d]
/usr/lib/libc.so.6(__libc_start_main+0xf1)[0x7fad72ef4291]
```

**Comment by arcan1s** [comment]
```
[KCrash Handler]
#6  0x00007f303c2bf04f in raise () at /usr/lib/libc.so.6
#7  0x00007f303c2c047a in abort () at /usr/lib/libc.so.6
#8  0x00007f303c2fcc50 in __libc_message () at /usr/lib/libc.so.6
#9  0x00007f303c302fe6 in malloc_printerr () at /usr/lib/libc.so.6
#10 0x00007f303c305411 in _int_malloc () at /usr/lib/libc.so.6
#11 0x00007f303c306d44 in malloc () at /usr/lib/libc.so.6
#12 0x00007f303ca60015 in QArrayData::allocate(unsigned long, unsigned long, unsigned long, QFlags<QArrayData::AllocationOption>) () at /usr/lib/libQt5Core.so.5
#13 0x00007f303cae4573 in QString::QString(int, Qt::Initialization) () at /usr/lib/libQt5Core.so.5
#14 0x00007f303cc952fd in  () at /usr/lib/libQt5Core.so.5
#15 0x00007f303cae9e92 in QString::fromUtf8_helper(char const*, int) () at /usr/lib/libQt5Core.so.5
#16 0x00007f303cae9f06 in QString::fromAscii_helper(char const*, int) () at /usr/lib/libQt5Core.so.5
#17 0x00007f2f8264d3bb in AWDataAggregator::setData(QString const&, float, float) () at /usr/lib/qt/qml/org/kde/plasma/private/awesomewidget/libawplugin.so
#18 0x00007f2f8264b778 in AWDataAggregator::setData(QHash<QString, QVariant> const&) () at /usr/lib/qt/qml/org/kde/plasma/private/awesomewidget/libawplugin.so
#19 0x00007f2f8264ad41 in AWDataAggregator::dataUpdate(QHash<QString, QVariant> const&) () at /usr/lib/qt/qml/org/kde/plasma/private/awesomewidget/libawplugin.so
#20 0x00007f303cc64659 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#21 0x00007f2f8269a5f3 in AWDataAggregator::updateData(QHash<QString, QVariant> const&) () at /usr/lib/qt/qml/org/kde/plasma/private/awesomewidget/libawplugin.so
#22 0x00007f2f8267de10 in AWKeys::updateTextData() () at /usr/lib/qt/qml/org/kde/plasma/private/awesomewidget/libawplugin.so
#23 0x00007f303cc64659 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#24 0x00007f303cc716d8 in QTimer::timerEvent(QTimerEvent*) () at /usr/lib/libQt5Core.so.5
#25 0x00007f303cc65473 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#26 0x00007f303dba3e0c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#27 0x00007f303dbab581 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#28 0x00007f303cc38de0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#29 0x00007f303cc8c6ae in QTimerInfoList::activateTimers() () at /usr/lib/libQt5Core.so.5
#30 0x00007f303cc8cbd1 in  () at /usr/lib/libQt5Core.so.5
#31 0x00007f303762f587 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#32 0x00007f303762f7f0 in  () at /usr/lib/libglib-2.0.so.0
#33 0x00007f303762f89c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#34 0x00007f303cc8d70f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#35 0x00007f303cc3723a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#36 0x00007f303cc3f73c in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#37 0x000000000041c9d2 in  ()
#38 0x00007f303c2ac291 in __libc_start_main () at /usr/lib/libc.so.6
#39 0x000000000041cd5a in _start ()
```

**Comment by arcan1s** [comment]
didnt see crash after plasma updates for some time
